### PR TITLE
WIP Gopher bugfix

### PR DESCRIPTION
**Pull request by asmodehn**
A set of bugfix for annoying things for gopher : 
- [x] ROS Param interface fixes
- [x] Fixing slow service/topics interfacing (one per update), even if discovery is fast...
- [ ] ~~Exposing Timeout to client to allow user customization~~ => LATER
- [x] Investigate topics conflict with gateway behavior, in case a simple fix is possible (list endpoints ?) relates to https://github.com/asmodehn/rostful/issues/92

And, if time allows, a new version release after that. Required to stabilize things.

### CODE REVIEW

**Comment by asmodehn** [comment]
note : Travis failed because of timeouts when using ROS... might be an opportunity to optimize things ?

**Comment by asmodehn** [comment]
Ah no thats because pyros_test package hasn't been release with changes yet...

**Comment by stonier** [comment]
Do you want to merge this in and work on the remaining two issues separately? Solves the first problem for me.

**Comment by asmodehn** [comment]
I still need to solve the problem of deleting topics for multiple pyros
instance (our case for concert). After that we can merge it. I ll let you
know.

**Comment by stonier** [comment]
ok

**Comment by asmodehn** [comment]
@stonier This version is managing topic/service/param going up and down much better than before. I am using the ros param server to keep track of multiple pyros instances.

But it still has issues with user nodes (rostful/celeros) going down (does not cleanup). We would need to review how they start and are killed, signal handling and all... https://github.com/asmodehn/pyros/issues/105

But as this is not in our usecase for now I think we can merge this and start using it.

**Comment by asmodehn** [comment]
We might have a performance issue... on a gopher v2.0 robot, CPU usage oscillate between 15% to 25 % (cache enabled). I ll need to investigate more...

**Comment by asmodehn** [comment]
After some profiling (multiple nodes with pubs coming up and down, while looping rosinterface update, with and without connection cache), I couldn't find any obvious bottleneck in the code.
So I think we should merge this and move forward. Ultimately one of the two pyros instance will be gone from the robot.

**Comment by asmodehn** [comment]
This seems finally ready for use, after a lot of improvements. podium simulation working OK.
Testing on actual gopher robot to validate performance improvements : 

@stonier with gopher_concert (cache enabled) : 
- rostful [1..3]%CPU
- celeros [1..3]%CPU
- gateway [2..6]%CPU

So it s quite nice now :-)

**Pull request merged**
